export const GET_GNOMES = 'GET_GNOMES';
export const GNOMES_LOADING = 'GNOMES_LOADING';

export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const GET_PENDINGS = 'GET_PENDINGS';
export const ADD_PENDING = 'ADD_PENDING';
export const DELETE_PENDING = 'DELETE_PENDING';

export const GET_RECENTS = 'GET_RECENTS';
export const ADD_RECENT = 'ADD_RECENT';